export enum Color {
    PRIMARY_BACKGROUND_COLOR = '#000025',
    PRIMARY_TEXT_COLOR = '#ffffff',
    SECONDARY_BACKGROUND_COLOR = '#ffffff',
    SECONDARY_TEXT_COLOR = '#000025',
    TERNARY_BACKGROUND_COLOR = '#EBEBEB',
}